### ISSUE TITLE
[FEATURE] Retry on failed proxy request

### ISSUE THREAD

**Issue by dwisiswant0** [kitabisa/mubeng#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hastalamuerte** [comment]
Extra needed function . 
Request not give a response after setted timeout it repeated by another proxy. etc..

Also can you tell plz If I use -s (sync) function - will it reduce multitreading to 1 tread? 
Maybe function to repeat error req (timeout) will be better than sync.

**Comment by dwisiswant0** [comment]
Close as completed in [v0.16.0](https://github.com/kitabisa/mubeng/releases/tag/v0.16.0).
