### ISSUE TITLE
[FEATURE] Not show debug connections on console and multi-threading support

### ISSUE THREAD

**Issue by Outcalled** [kitabisa/mubeng#114]
**Is your feature request related to a problem? Please describe.**
I do not like that everytime I launch the rotating proxy server, it just always fills everything up with the connections being made... 
I also would like multi-threading support being added for VPS 4-64+ cores.

**Describe the solution you'd like**
Making an option to make the console be clear from all debugging stuff and adding multi-threading for better performance.

**Describe alternatives you've considered**
Nope.

**Additional context**
Nope.

**Comment by dwisiswant0** [comment]
Just don't use `--verbose` flag.
