### ISSUE TITLE
Error getting https websites

### ISSUE THREAD

**Issue by unstppbl** [kitabisa/mubeng#12]
**Describe the bug**

Trying to get https://example.org through mubeng

**To Reproduce**
Run mubeng, try to `curl -x http://mubenghost:mubengport example.org`

```bash
./mubeng -f ../proxies.txt -a localhost:8080 -c -v
2021/03/03 22:10:15 [INFO] ▶ [PID: 29823] Starting proxy server on localhost:8080
2021/03/03 22:10:35 [001] WARN: Cannot handshake client example.org:443 local error: tls: bad record MAC
```

**Expected behavior**

Body of example.org site

**Comment by dwisiswant0** [comment]
Can you please try with protocol scheme, @unstppbl? `https://example.org`.

**Comment by unstppbl** [comment]
> Can you please try with protocol scheme, @unstppbl? `https://example.org`.

Tried already, same thing. Were you able to reproduce?

**Comment by dwisiswant0** [comment]
> > Can you please try with protocol scheme, @unstppbl? `https://example.org`.
> 
> Tried already, same thing. Were you able to reproduce? Or am I doing something wrong?

I'm not sure since this working well by my side. Try with actual website, e.g. https://www.facebook.com or https://twitter.com. Then let me know.

**Comment by alli03106** [comment]
A

**Comment by Potato334343** [comment]
I'm having the same issue

**Comment by zoli** [comment]
This is same as #72 I think. You should install the certificate.
