### ISSUE TITLE
[FEATURE] HTTPS proxy as source

### ISSUE THREAD

**Issue by cnbeining** [kitabisa/mubeng#125]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I want to use HTTPS proxy as source.

**Describe the solution you'd like**

Give HTTPS proxy similar support as HTTP proxy.

**Describe alternatives you've considered**

N/A

**Additional context**

Reference: https://www.nsoftware.com/kb/articles/legacy/sbb/4-http-https.rst

**Comment by MXall0c** [comment]
this will be a gigantic help.

**Comment by cnbeining** [comment]
@MXall0c feel free to try out at https://github.com/kitabisa/mubeng/pull/133 before the PR is merged.
