### ISSUE TITLE
[FEATURE] Live-reload proxy pool for proxy IP rotator

### ISSUE THREAD

**Issue by Trapshell** [kitabisa/mubeng#137]
first
Gotta admit it's a great piece of work❤️
There is a suggestion that I hope can be adopted.
System: win11
-f ip.txt（Specify the txt file）
It would be better if it was dynamic
I try to use python to extract IP and modify IP.txt content.
But the new txt data is not recognized after the program runs.

A small suggestion
May good luck be with you

**Comment by dwisiswant0** [comment]
Thanks for suggesting this, @Trapshell, and I think it's worth adding.

**Comment by dwisiswant0** [comment]
Hey @Trapshell, now it's packed on [v0.10.0](https://github.com/kitabisa/mubeng/releases/tag/v0.10.0). Bump yours with `mubeng --update`.
