### ISSUE TITLE
http://mubeng/cert DONT WORK PLS HELP

### ISSUE THREAD

**Issue by Cr4zyM4n3** [kitabisa/mubeng#149]
2022/09/25 21:28:32 [DEBU] ▶ 170.187.203.113:49936 GET http://mubeng/cert
2022/09/25 21:28:33 [DEBU] ▶ 170.187.203.113:49936 500 Internal Server Error
2022/09/25 21:28:33 [DEBU] ▶ 170.187.203.113:49936 GET http://mubeng/favicon.ico
2022/09/25 21:28:33 [DEBU] ▶ 170.187.203.113:49936 503 Service Unavailable
2022/09/25 21:28:34 [DEBU] ▶ 170.187.203.113:49936 GET http://mubeng/cert
2022/09/25 21:28:34 [DEBU] ▶ 170.187.203.113:49936 500 Internal Server Error
2022/09/25 21:28:34 [DEBU] ▶ 170.187.203.113:49936 GET http://mubeng/favicon.ico
2022/09/25 21:28:34 [DEBU] ▶ 170.187.203.113:49936 503 Service Unavailable

**Comment by Cr4zyM4n3** [comment]
I PAY IF SOMEONE HELP ME

**Comment by Cr4zyM4n3** [comment]
2022/09/25 21:26:22 [INFO] ▶ [PID: 683] Starting proxy server on :8080
2022/09/25 21:26:34 [DEBU] ▶ 189.302.44.183:60896 GET http://mubeng/cert
2022/09/25 21:26:34 [DEBU] ▶ 189.302.44.183:60896 500 Internal Server Error
2022/09/25 21:26:34 [DEBU] ▶ 189.302.44.183:60896 GET http://mubeng/favicon.ico
2022/09/25 21:26:34 [ERRO] ▶ 189.302.44.183:60896 Get "http://mubeng/favicon.ico             ": context canceled
2022/09/25 21:26:37 [DEBU] ▶ 189.302.44.183:60912 GET http://50.116.23.57/cert
2022/09/25 21:26:37 [DEBU] ▶ 189.302.44.183:60912 502 Bad Gateway
2022/09/25 21:26:37 [DEBU] ▶ 189.302.44.183:60912 GET http://50.116.23.57/favico             n.ico
2022/09/25 21:26:37 [ERRO] ▶ 189.302.44.183:60912 Get "http://50.116.23.57/favic             on.ico": context canceled

**Comment by dwisiswant0** [comment]
http://**mubeng**/cert, **mubeng** means your IP.
