### ISSUE TITLE
[BUG] Page stop loading

### ISSUE THREAD

**Issue by lheintzmann** [kitabisa/mubeng#175]
**Describe the bug**

When i want to access a website through mubeng configured as a proxy in firefox, the page don't load, and i see a message in the console:
`[052] WARN: Cannot write TLS response body from mitm'd client: http: read on closed response body`

**Environment (please complete the following information):**

- OS: Kali Linux
- OS version: `Linux fsociety 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux`
- mubeng Version: Mubeng 0.13.0

**Comment by dwisiswant0** [comment]
The `[\d{3}]` error prefix comes from Goproxy. This may be because the proxy is timeout but still waiting for a response. Try to rotate it - refresh the proxy pool.

**Comment by dwisiswant0** [comment]
This should be fixed in [v0.13.2](https://github.com/kitabisa/mubeng/releases/tag/v0.13.2). Bump yours with `mubeng -u`.
