### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Y-GM** [kitabisa/mubeng#193]
**Is your feature request related to a problem? Please describe.**
There is a problem with the certificate. The certificate is very bad.. it is not accepted by the websites

**Describe the solution you'd like**
Use without a security certificate

**Describe alternatives you've considered**
Use without a security certificate like this: https://github.com/DKingAlpha/RPS

**Additional context**
The program is very good.. but the certificate causes many problems

**Comment by dwisiswant0** [comment]
You can just [install SSL cert](https://github.com/kitabisa/mubeng#install-ssl-certificate) easily.

**Comment by Y-GM** [comment]
> You can just [install SSL cert](https://github.com/kitabisa/mubeng#install-ssl-certificate) easily.

I want to use it without a certificate

**Comment by dwisiswant0** [comment]
> > You can just [install SSL cert](https://github.com/kitabisa/mubeng#install-ssl-certificate) easily.
> 
> I want to use it without a certificate

You can do that but only for HTTP, not HTTPS.
