### ISSUE TITLE
[FEATURE]--check   Add progress prompt

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [kitabisa/mubeng#215]
I hope there is a progress prompt

**Comment by Laura0xiaoshizi** [comment]
check  multithreading

**Comment by dwisiswant0** [comment]
> check multithreading

Proxy checker is already multi-threading with `-g`/`--goroutine` flag.

**Comment by Laura0xiaoshizi** [comment]
> > check multithreading
> 
> Proxy checker is already multi-threading with `-g`/`--goroutine` flag.

tks,Add progress prompt
