### ISSUE TITLE
[BUG] tls: bad record MAC

### ISSUE THREAD

**Issue by panterlo** [kitabisa/mubeng#219]
**Describe the bug**

Some wierd things are happening when configuring an https proxy in the proxylist.

**To Reproduce**

```yaml
> mubeng -f proxylist.txt -a localhost:8089
```
Proxylist contains one row:
https://"replace with ip":3129

This ip runs a Squid proxy with this configuration:
https_port 3129 cert=/etc/squid/certs/squid-ca-cert-key.pem

**Expected behavior**

Trying to run a curl against mubeng gives the following error:
curl --proxy "localhost:8089" https://api.myip.com

2023/11/06 14:42:19 [001] WARN: Cannot handshake client api.myip.com:443 local error: tls: bad record MAC

Running the same curl but pointing directly to the Squid proxy gives no errors:
curl --proxy-insecure --proxy "https://"replace with ip":3129" https://api.myip.com
{"ip":"","country":","":""}

**Screenshots**

![image](https://github.com/kitabisa/mubeng/assets/320204/c0daa35e-3a00-4ae7-b0f8-303baffc54cc)

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]: Mubeng on Windows, Squid on Arch Linux
- OS version: [uname -a] Windows 11
- mubeng Version: [mubeng -V] v0.14.1

**Additional context**
I am trying to get my head around how to configure secure https proxy servers that works with mubeng. E.g

Requesting client <--HTTP (or HTTPS--> Mubeng <-- HTTPS ONLY --> Squid(or any other proxy)

**Comment by dwisiswant0** [comment]
Hi @panterlo,

Have you tried using a squid proxy on a different server with another IP? Also, do you face the same issue when your squid proxy server is set up with HTTP?

Thanks!

**Comment by vimagick** [comment]
I still have the issue.

```bash
$ echo "http://x.x.x.x:8080" | mubeng -v -a 0.0.0.0:3128 -f -
2024/09/23 07:08:23 [001] WARN: Cannot handshake client ipinfo.io:443 EOF

$ curl localhost:3128/cert > mubeng.crt

$ curl --cacert mubeng.crt -x localhost:3128 https://ipinfo.io
curl: (77) error setting certificate file: mubeng.crt
```
