### ISSUE TITLE
Log more data with `--output` flag

### ISSUE THREAD

**Issue by MMquant** [kitabisa/mubeng#223]
It would be nice if the `--output` flag logged more details.
Currently it logs only live proxies. There could be additionally the location and the response time in ms.

For example the output file could output data in this format

```
[RU] [89.250.152.76] [2500] http://89.250.152.76:8080
```

I would love to filter the proxies by the response time based on the work I'm currently doing. Sometimes I need fast proxies and sometimes it doesn't matter.

The only way I can sort the proxies by response time is to run second `mubeng --check ...` with shorter `--timeout`.

**Comment by dwisiswant0** [comment]
That's a solid idea, but it looks like to store that info, we might need to introduce new flags, like specifying the output format the user prefers, whether it's JSONL or CSV. This way, we can offer more details than just the checker results. However, we need to think about this output flag design carefully since it also applies to logging proxy servers.

**Comment by dwisiswant0** [comment]
The original design for the existing output _(checker specific)_ was tailored for direct feeding into the proxy server from the output file:
1. `mubeng -c -f proxies.txt -o live.txt`
2. `mubeng -a :8080 -f live.txt`

Looking at your current scenario, it seems achievable using either the `--timeout` or `--only-cc` flag.

**Comment by MMquant** [comment]
The easiest would be to add a flag to simply log all details let's say in this format

```
[RU] [89.250.152.76] [2500] http://89.250.152.76:8080
```

the format really doesn't matter you can parse it later.

So you could for example use two output fags in one command

```
mubeng -c -f proxies.txt -o live.txt -d live-details.txt`
```

That way you have both outputs - the one you need for feed the mubeng and the one for further processing.

**Comment by MMquant** [comment]
details ... but use a flag which you are comfort with. `-d` flag often stands for debug.

If you accept two letter flags you could use `-od`, Ouput Detailed.
