### ISSUE TITLE
[BUG] Does not work in `Docker`

### ISSUE THREAD

**Issue by sequencerr** [kitabisa/mubeng#224]
**Describe the bug**
```sh
yrch@debian:~/mubeng$ docker run ghcr.io/kitabisa/mubeng -u

           _   v0.14.1
 _____ _ _| |_ ___ ___ ___
|     | | | . | -_|   | . |
|_|_|_|___|___|___|_|_|_  |
                      |___|
 infosec@kitabisa.com
FTL] Error! Get "https://api.github.com/repos/kitabisa/mubeng/tags": dial tcp: lookup api.github.com on 192.168.191.2:53: read udp 172.17.0.2:40738->192.168.191.2:53: i/o timeout
yrch@debian:~/mubengbin/mubeng -u

           _   v0.14.1
 _____ _ _| |_ ___ ___ ___
|     | | | . | -_|   | . |
|_|_|_|___|___|___|_|_|_  |
                      |___|
 infosec@kitabisa.com

[INF] It's the latest stable version, no need to update.
yrch@debian:~/mubeng$ 
```

**Screenshots**
![image](https://github.com/kitabisa/mubeng/assets/45060278/6e2a2eb2-fab6-4c8c-93bc-642036dbe17f)

**Environment (please complete the following information):**

- OS: linux
- OS version: `Linux debian 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
Machine:
  Type: Vmware System: VMware product: VMware Virtual Platform v: N/A  `     
- mubeng Version: `yrch@debian:~/mubeng$ docker run --rm ghcr.io/kitabisa/mubeng -V
mubeng version v0.14.1
yrch@debian:~/mubeng$ bin/mubeng -V
mubeng version v0.14.1`

**Comment by dwisiswant0** [comment]
That's the issue with your DNS.

**Comment by sequencerr** [comment]
> That's the issue with your DNS.

I don't have this issue without docker. This may be docker or mubeng.
Actually none of lib commands works in docker. Update cmd is just easy to display. And without docker checker works but server only starts (does not provide any proxy)

**Comment by sequencerr** [comment]
@dwisiswant0
