### ISSUE TITLE
[BUG] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by naomipasherr** [kitabisa/mubeng#225]
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x81aafa]**

mubeng works correctly when we use in sqlmap nuclei and etc....
BUT some tools like Acunetix, Appscan when use proxy server, mubeng crushes

I guess maybe some packet corrupt but mubeng not handle it. please follow screenshot

**Screenshots**
![image](https://github.com/kitabisa/mubeng/assets/156658310/1b215463-8c0b-4dc9-93f3-066882b2889b)

- OS: linux
- OS version: Linux 5.15.0-91-generic 
- mubeng Version: v0.14.1

**Comment by dwisiswant0** [comment]
Hi @naomipasherr, thanks for reporting this. Could you please provide more details (stack trace) about the crash in plain text?

**Comment by naomipasherr** [comment]
how i can get stack trace in ubuntu?

**Comment by dwisiswant0** [comment]
> how i can get stack trace in ubuntu?

I mean the full message of the panic message.

**Comment by naomipasherr** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x81aafa]

goroutine 38 [running]:
ktbs.dev/mubeng/internal/server.(*Proxy).onRequest.func1()
        /app/internal/server/handler.go:45 +0x5a
created by ktbs.dev/mubeng/internal/server.(*Proxy).onRequest
        /app/internal/server/handler.go:44 +0x37d

**Comment by dwisiswant0** [comment]
Hi @naomipasherr, thanks for providing that information. May I know how you use the mubeng (like the command)?

**Comment by dwisiswant0** [comment]
Reopening this while waiting for your reply.

**Comment by dwisiswant0** [comment]
Closing this as I didn't get a follow-up.
