### ISSUE TITLE
WARN: Cannot handshake client www.google.com:443

### ISSUE THREAD

**Issue by Imran407704** [kitabisa/mubeng#228]
**WARN: Cannot handshake client www.google.com:443**

When I run Mubeng and run my Personal Script for Google Dorking mubeng says this "WARN: Cannot handshake client www.google.com:443" and my script didn't give me the results.

**Command**

mubeng_0.14.2_linux_amd64 -a localhost:8089 -f live_proxies.txt -r 1 -v 

**Screenshots**
I have attached the Screenshot for reference.
![mubeng_error](https://github.com/kitabisa/mubeng/assets/51431951/df23501c-287b-4b51-9112-db7fc4a58dea)

- OS: linux
- OS version: Linux kali 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
- mubeng Version: mubeng_0.14.2_linux_amd64
mubeng older version has give me same issue.

**Comment by dwisiswant0** [comment]
You need to install GoProxy CA cert[^1] on the OS or browser perspective.

[^1]: https://github.com/kitabisa/mubeng#install-ssl-certificate
