### ISSUE TITLE
Issue with SMTP Protocol: Cannot Handshake Client Error

### ISSUE THREAD

**Issue by Y-GM** [kitabisa/mubeng#256]
---

**Describe the bug**  
When attempting to use the SMTP protocol through Mubeng, the connection fails with an error. The log shows a `Cannot handshake client ... EOF` message, indicating that Mubeng is unable to complete the handshake with the SMTP server.

**To Reproduce**  
```yaml
> mubeng -a :8080 -f proxies.txt -w
```
In the `proxies.txt` file, the proxy is configured with SMTP details as follows:
```
http://k2pqyc1der1biug-country-fr-session-*****-lifetime-2:rs3es3mvo*****@rp.proxyscrape.com:6060
```

**Expected behavior**  
Mubeng should successfully establish a handshake with the SMTP server, allowing SMTP traffic to flow through the proxy.

**Screenshots**  
![mstsc_hSiw9b5ZgO](https://github.com/user-attachments/assets/db5b5a61-312b-43bd-879a-3068d28fff2d)

**Environment :**
- OS: Windows
- Mubeng Version: v0.18.0 

**Additional context**  
Full error log:
```
2024/10/28 15:09:17 [001] WARN: Cannot handshake client 212.27.48.4:587 EOF
```

Is there any specific configuration needed for SMTP protocol support in Mubeng, or is SMTP protocol unsupported?

---

**Comment by dwisiswant0** [comment]
> or is SMTP protocol unsupported?

Unfortunately, it is not supported.
