### ISSUE TITLE
[FEATURE] Proxy checker retries

### ISSUE THREAD

**Issue by thefirst100yearsaredifficult** [kitabisa/mubeng#257]
Hello, 
wanted to ask is there an option to retry the proxies when I use the checker option?

**Comment by dwisiswant0** [comment]
Thanks for raising this!

The `--max-retries` option is now a general option in [v0.19.0](https://github.com/kitabisa/mubeng/releases/tag/v0.19.0). It works for both proxy checker and proxy IP rotator server.

Bump with `mubeng --update`.
