### ISSUE TITLE
[BUG] Unable to use with own list

### ISSUE THREAD

**Issue by h0nus** [kitabisa/mubeng#32]
**Describe the bug**

using mubeng gives error. `[FTL] Error! open /home/x/proxies.txt: has no valid proxy URLs.`

**To Reproduce**

run mubeng with `mubeng -f /home/x/proxies.txt --check -v`

**Expected behavior**

To check or to rotate with my list

![image](https://user-images.githubusercontent.com/23401728/118589741-4890d100-b7a1-11eb-8f59-dd134ad57b4a.png)

**Environment (please complete the following information):**

- OS: Kali Linux on WSL
- OS version: `Linux DESKTOP-E97AU3J 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux`
- mubeng Version: `mubeng version v0.4.5`

**Additional context**
My list is done like this:
```
https://x:1080
https://x:1080
https://x:1080
https://x:1080
https://x:1080
```
![image](https://user-images.githubusercontent.com/23401728/118589917-a9b8a480-b7a1-11eb-96be-9899d1c9c01f.png)

**Comment by dwisiswant0** [comment]
This isn't a bug. Unfortunately, mubeng doesn't support HTTPS proxy protocol. See [Limitations](https://github.com/kitabisa/mubeng#limitations).

**Comment by h0nus** [comment]
Oh ok, sorry 
i saw the example and thought it was possibile,
thanks, any idea/eta on this?
i really like this project.

**Comment by VioletFlare** [comment]
Had me pulling my hair out. Why did you put https in the examples if you can't use it?
