### ISSUE TITLE
[FEATURE] Need Basic Auth feature 

### ISSUE THREAD

**Issue by secureITmania** [kitabisa/mubeng#34]
How can I specify the username and password to the proxy?.  I don't see this feature is available in the tool.

**Comment by dwisiswant0** [comment]
Is this for the proxy server or connecting to a proxy client, @secureITmania?

**Comment by secureITmania** [comment]
> 
> 
> Is this for the proxy server or connecting to a proxy client, @secureITmania?

I have proxy ips(alive.txt) that need to provide a username and password to connect.

**Comment by dwisiswant0** [comment]
Put on the list like this, @secureITmania:

```
http://username:password@ip:port/
```

Let us know what happens then.

**Comment by secureITmania** [comment]
Thanks, It is working 👍

**Comment by Nag1bat0r** [comment]
Same question for socks5 with username:password

**Comment by dwisiswant0** [comment]
> Same question for socks5 with username:password

Should be like this, @Nag1bat0r:

> Put on the list like this, @secureITmania:
> 
> ```
> http://username:password@ip:port/
> ```
> 
> Let us know what happens then.

But change that `http` protocol to `socks5`.

**Comment by Nag1bat0r** [comment]
"Should be" but didn't work :(
Check utility could not find any valid proxy, but they "good" cause i checked them before for validity.

**Comment by Nou4r** [comment]
Yep, doesn't work for socks5 sadly, a fix would be really really nice.

**Comment by dwisiswant0** [comment]
> Same question for socks5 with username:password

See #57.
