### ISSUE TITLE
[BUG]not use https

### ISSUE THREAD

**Issue by moyuwa** [kitabisa/mubeng#38]
proxies.txt  as:
https://163.204.92.67:9999
https://42.7.7.38:9999
......

exe error

transport.go code ：
switch proxyURL.Scheme {
	case "socks5":
		tr = &http.Transport{
			Dial: dialer.Dial,
		}
	case "http":
		tr = &http.Transport{
			Proxy: http.ProxyURL(proxyURL),
		}
	default:
		return nil, fmt.Errorf("unsupported proxy protocol scheme: %s", proxyURL.Scheme)
	}

what is ‘https’？

**Comment by dwisiswant0** [comment]
This isn't a bug. Unfortunately, mubeng doesn't support HTTPS proxy protocol. See [Limitations](https://github.com/kitabisa/mubeng#limitations).
