### ISSUE TITLE
[BUG] Not compatible with mac?

### ISSUE THREAD

**Issue by CharlieS1103** [kitabisa/mubeng#41]
**Describe the bug**

According to the read me, this works with mac, however neither the ARM binary nor the docker seemed to work

**To Reproduce**

Try to use it on mac

**Expected behavior**

It works.

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac
- OS version: 10.15.7
- mubeng Version: Latest

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by dwisiswant0** [comment]
Have you tried the pre-built version for darwin from [releases page](https://github.com/kitabisa/mubeng/releases), @CharlieS1103?

**Comment by CharlieS1103** [comment]
Oh, works. Ty.
