### ISSUE TITLE
[BUG] fix logic bug in proxymanager that always use 2nd proxy at the beginning

### ISSUE THREAD

**Issue by ganuonglachanh** [kitabisa/mubeng#56]
in proxymanager.go, line 33:

	manager := &ProxyManager{Proxies: []string{}, CurrentIndex: 0}

it should be CurrentIndex: **`-1`**

**Comment by dwisiswant0** [comment]
Hi, @ganuonglachanh. It should be fixed on [v0.5.1](https://github.com/kitabisa/mubeng/releases/tag/v0.5.1).

Thanks again for your report!
