### ISSUE TITLE
[BUG] Proxy auth works for HTTP but NOT for socks5!

### ISSUE THREAD

**Issue by Nou4r** [kitabisa/mubeng#57]
^title.

**Comment by dwisiswant0** [comment]
Hi, @Nou4r. This issue should be resolved on [v0.5.2](https://github.com/kitabisa/mubeng/releases/tag/v0.5.2).

Now you can use authorization for SOCKSv5 (e.g. `socks5://USER[:PASS]@IP:PORT`).

**Comment by Foxtrod89** [comment]
> Hi, @Nou4r. This issue should be resolved on [v0.5.2](https://github.com/kitabisa/mubeng/releases/tag/v0.5.2).
> 
> Now you can use authorization for SOCKSv5 (e.g. `socks5://USER[:PASS]@IP:PORT`).

doesn't work, no response
