### ISSUE TITLE
[FEATURE] IP Whitelist / Proxy USER:AUTH Protection

### ISSUE THREAD

**Issue by JReverse** [kitabisa/mubeng#77]
**Is your feature request related to a problem? Please describe.**
IP Whitelist / Proxy USER:AUTH Protection to prevent abuse

**Describe the solution you'd like**
IP Whitelist / Proxy USER:AUTH Protection to prevent abuse

**Describe alternatives you've considered**

**Additional context**

**Comment by dwisiswant0** [comment]
I believe this is already in the latest version, [v0.8.0](https://github.com/kitabisa/mubeng/releases/tag/v0.8.0). Grab 'em!
