### ISSUE TITLE
[FEATURE] Add auth in proxy server in the flag -a

### ISSUE THREAD

**Issue by vay3t** [kitabisa/mubeng#83]
**Is your feature request related to a problem? Please describe.**
possibility of creating a server with the flag -a that has basic authentication

**Describe the solution you'd like**
add the possibility of reading a configuration file the argument where are the credentials and/or the host/port to use

**Additional context**
This is useful when you want to use a server as an IP rotator and share it with your trusted colleagues.

**Comment by dwisiswant0** [comment]
Closing as duplicate to #77.

**Comment by dwisiswant0** [comment]
I believe this is already in the latest version, [v0.8.0](https://github.com/kitabisa/mubeng/releases/tag/v0.8.0). Grab 'em!
