### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by craciu25yt** [kitabisa/mubeng#95]
**Is your feature request related to a problem? Please describe.**
Yes. It say I need say like http://ip:port and I have one list of 65k proxies and idk what proxy is http, socks5...

**Describe the solution you'd like**
Something like the program try to find the type
**Describe alternatives you've considered**
idk
**Additional context**

**Comment by dwisiswant0** [comment]
I don't know what are you talking about, can explain more?
